################################################################################
# 生成文件和参数文件使用这些宏。
# 如果在路径中包含空格与不能使用引号（"），
# 一个使用反斜杠（\）来转义空格的宏的_ESCAPE版本被加上。
################################################################################

export NETIF=E:/0_Project/rep_local/proj-dev-2024/project/LwIP/src/netif
export GNU_Make_Install_DirEnv=$(CWInstallLocationEnv)/gnu/bin
export ProjDirPath=E:/0_Project/rep_local/proj-dev-2024/project/xyp1022_project/projects/CW/xyp1022_project-core00
export CWInstallLocationEnv=D:/Freescale/CW_PA_v10.5.1
export PAGccAeabiE5500DirEnv=$(CWInstallLocationEnv)/Cross_Tools/gcc-4.9.2-Ee5500-aeabi/bin
export BOARD=E:/0_Project/rep_local/proj-dev-2024/project/xyp1022_project/board
export COREMARK=E:/0_Project/rep_local/proj-dev-2024/project/xyp1022_project/libs/coremark
export MEMMANG=E:/0_Project/rep_local/proj-dev-2024/project/FreeRTOS/FreeRTOS-Kernel/portable/MemMang
export IPV4=E:/0_Project/rep_local/proj-dev-2024/project/LwIP/src/core/ipv4
export LIBS1=E:/0_Project/rep_local/proj-dev-2024/project/xyp1022_project/libs
export DRIVER=E:/0_Project/rep_local/proj-dev-2024/project/xyp1022_project/driver
export SOURCES=E:/0_Project/rep_local/proj-dev-2024/project/xyp1022_project/ThirdLib/Sources
export CORE=E:/0_Project/rep_local/proj-dev-2024/project/LwIP/src/core
export API=E:/0_Project/rep_local/proj-dev-2024/project/LwIP/src/api
export SOURCE=E:/0_Project/rep_local/proj-dev-2024/project/xyp1022_project/libs/ff15/source
export ARCH=E:/0_Project/rep_local/proj-dev-2024/project/xyp1022_project/projects/arch
export THIRDLIB=E:/0_Project/rep_local/proj-dev-2024/project/xyp1022_project/ThirdLib
export PPC=E:/0_Project/rep_local/proj-dev-2024/project/FreeRTOS/FreeRTOS-Kernel/portable/GCC/PPC
export FREERTOS_KERNEL=E:/0_Project/rep_local/proj-dev-2024/project/FreeRTOS/FreeRTOS-Kernel
export LIB=E:/0_Project/rep_local/proj-dev-2024/project/xyp1022_project/ThirdLib/Lib
export PROJECTS=E:/0_Project/rep_local/proj-dev-2024/project/xyp1022_project/projects
export PPC_DRIVER=E:/0_Project/rep_local/proj-dev-2024/project/xyp1022_project/ppc_driver
