
// RW REGISTER LIST

 #define	 reg_rc_value                    		  0xb00		,  25		,  18		
 #define	 reg_rcd_value                   		  0xb00		,  17		,  10		
 #define	 reg_ref_value                   		  0xb00		,  9		,  0		
 #define	 reg_ras_value                   		  0xb04		,  25		,  18		
 #define	 reg_rp_value                    		  0xb04		,  17		,  10		
 #define	 reg_rfc_value                   		  0xb04		,  9		,  0		
 #define	 reg_trtp_value                  		  0xb08		,  31		,  24		
 #define	 reg_twr_value                   		  0xb08		,  23		,  16		
 #define	 reg_twtr_value                  		  0xb08		,  15		,  8		
 #define	 reg_rrd_value                   		  0xb08		,  7		,  0		
 #define	 reg_auto_refresh_en             		  0xb0c		,  29		,  29		
 #define	 reg_init_start                  		  0xb0c		,  28		,  28		
 #define	 reg_bk_faw_cnt                  		  0xb0c		,  27		,  20		
 #define	 reg_tccd_l_value                		  0xb0c		,  19		,  12		
 #define	 reg_bank_size                   		  0xb0c		,  11		,  10		
 #define	 reg_row_size                    		  0xb0c		,  9		,  6		
 #define	 reg_col_size                    		  0xb0c		,  5		,  2		
 #define	 reg_burst_type                  		  0xb0c		,  1		,  0		
 #define	 reg_rank_select                 		  0xb10		,  16		,  16		
 #define	 reg_hclk_mem_bist_sel           		  0xb10		,  15		,  15		
 #define	 reg_bist_mode_sel               		  0xb10		,  12		,  10		
 #define	 reg_bist_serial_wr_stop         		  0xb10		,  9		,  9		
 #define	 reg_bist_soft_rstn              		  0xb10		,  8		,  8		
 #define	 reg_bist_start                  		  0xb10		,  7		,  7		
 #define	 reg_bist_en                     		  0xb10		,  6		,  6		
 #define	 reg_bist_addr_pattern_sel       		  0xb10		,  5		,  3		
 #define	 reg_bist_data_pattern_sel       		  0xb10		,  2		,  0		
 #define	 reg_bist_start_addr             		  0xb14		,  31		,  0		
 #define	 reg_bist_end_addr               		  0xb18		,  31		,  0		
 #define	 reg_bist_data1                  		  0xb1c		,  31		,  0		
 #define	 reg_bist_data0                  		  0xb20		,  31		,  0		
 #define	 reg_load_mode1                  		  0xb24		,  31		,  16		
 #define	 reg_load_mode0                  		  0xb24		,  15		,  0		
 #define	 reg_load_mode3                  		  0xb28		,  31		,  16		
 #define	 reg_load_mode2                  		  0xb28		,  15		,  0		
 #define	 reg_load_mode5                  		  0xb2c		,  31		,  16		
 #define	 reg_load_mode4                  		  0xb2c		,  15		,  0		
 #define	 reg_load_mode11                 		  0xb30		,  31		,  16		
 #define	 reg_load_mode6                  		  0xb30		,  15		,  0		
 #define	 reg_load_mode14                 		  0xb34		,  31		,  16		
 #define	 reg_load_mode13                 		  0xb34		,  15		,  0		
 #define	 reg_load_mode12                 		  0xb38		,  31		,  16		
 #define	 reg_load_mode22                 		  0xb38		,  15		,  0		
 #define	 reg_bist_dm_cfg_value_en        		  0xb3c		,  28		,  28		
 #define	 reg_bist_dm_en                  		  0xb3c		,  27		,  27		
 #define	 reg_dfi_dram_clk_disable        		  0xb3c		,  26		,  26		
 #define	 reg_dfi_init_start              		  0xb3c		,  25		,  25		
 #define	 reg_load_mode_en                		  0xb3c		,  24		,  24		
 #define	 reg_load_mode_addr              		  0xb3c		,  23		,  16		
 #define	 reg_load_mode                   		  0xb3c		,  15		,  0		
 #define	 reg_odt_all_open                		  0xb40		,  17		,  17		
 #define	 reg_odt_enable                  		  0xb40		,  16		,  16		
 #define	 reg_ddr_odt_neg_value           		  0xb40		,  15		,  12		
 #define	 reg_ddr_odt_pos_value           		  0xb40		,  11		,  8		
 #define	 reg_bist_dm_cfg_value           		  0xb40		,  7		,  0		
 #define	 reg_lpddr23_load_mode_mrwzqcl   		  0xb44		,  31		,  16		
 #define	 reg_lpddr23_load_mode_mrwreset  		  0xb44		,  15		,  0		
 #define	 reg_bist_ddrc_tzqinit_x32       		  0xb48		,  31		,  24		
 #define	 reg_bist_ddrc_tzqlat            		  0xb48		,  23		,  16		
 #define	 reg_bist_ddrc_tckeh_x32         		  0xb48		,  15		,  8		
 #define	 reg_lpddr3_cke_l_x1024          		  0xb48		,  7		,  0		
 #define	 reg_lpddr3_init5_10us_x1024     		  0xb4c		,  29		,  23		
 #define	 reg_bist_ddrc_tmrw              		  0xb4c		,  22		,  19		
 #define	 reg_bist_ddrc_treset_l_x1024    		  0xb4c		,  18		,  11		
 #define	 reg_bist_ddrc_treset_h_x1024    		  0xb4c		,  10		,  0		
 #define	 reg_lpddr4_vref_wait_time       		  0xb50		,  7		,  0		


// RO REGISTER LIST
 #define	 reg_bist_error_addr_obs         		  0xb60		,  31		,  0		
 #define	 reg_data_bist_state             		  0xb64		,  25		,  19		
 #define	 reg_bist_error_cnt              		  0xb64		,  18		,  11		
 #define	 reg_bist_pass                   		  0xb64		,  10		,  10		
 #define	 reg_bist_done                   		  0xb64		,  9		,  9		
 #define	 reg_bist_state                  		  0xb64		,  8		,  2		
 #define	 phy_init_done                   		  0xb64		,  1		,  1		
 #define	 reg_init_done                   		  0xb64		,  0		,  0		
 #define	 reg_bist_act_data_obs0          		  0xb68		,  31		,  0		
 #define	 reg_bist_act_data_obs1          		  0xb6c		,  31		,  0		
 #define	 reg_bist_act_data_obs2          		  0xb70		,  31		,  0		
 #define	 reg_bist_act_data_obs3          		  0xb74		,  31		,  0		
 #define	 reg_bist_act_data_obs4          		  0xb78		,  31		,  0		
 #define	 reg_bist_act_data_obs5          		  0xb7c		,  31		,  0		
 #define	 reg_bist_act_data_obs6          		  0xb80		,  31		,  0		
 #define	 reg_bist_act_data_obs7          		  0xb84		,  31		,  0		
 #define	 reg_bist_act_data_obs8          		  0xb88		,  31		,  0		
 #define	 reg_bist_exp_data_obs0          		  0xb8c		,  31		,  0		
 #define	 reg_bist_exp_data_obs1          		  0xb90		,  31		,  0		
 #define	 reg_bist_exp_data_obs2          		  0xb94		,  31		,  0		
 #define	 reg_bist_exp_data_obs3          		  0xb98		,  31		,  0		
 #define	 reg_bist_exp_data_obs4          		  0xb9c		,  31		,  0		
 #define	 reg_bist_exp_data_obs5          		  0xba0		,  31		,  0		
 #define	 reg_bist_exp_data_obs6          		  0xba4		,  31		,  0		
 #define	 reg_bist_exp_data_obs7          		  0xba8		,  31		,  0		
 #define	 reg_bist_exp_data_obs8          		  0xbac		,  31		,  0		


