#define     PCIX1_REGS_BASE_ADDR        0x5EC80000
#define     PCIX1_CONFIG_BASE_ADDR      0x5EC00000
#define     PCIX1_IO_BASE_ADDR          0x58000000
#define     PCIX1_EXTRA_IO_BASE_ADDR    0x58800000
#define     PCIX1_SPECIAL_BASE_ADDR     0x5ED00000


#define     PCIX2_REGS_BASE_ADDR        0x7EC80000
#define     PCIX2_CONFIG_BASE_ADDR      0x7EC00000
#define     PCIX2_IO_BASE_ADDR          0x78000000
#define     PCIX2_EXTRA_IO_BASE_ADDR    0x78800000
#define     PCIX2_SPECIAL_BASE_ADDR     0x7ED00000




#define     PCICx_VENDID_OFFSET       0x00000000 
#define     PCICx_DEVID_OFFSET        0x00000002 
#define     PCICx_CMD_OFFSET          0x00000004 
#define     PCICx_STATUS_OFFSET       0x00000006 
#define     PCICx_REVID_OFFSET        0x00000008 
#define     PCICx_CLS_OFFSET          0x00000009 
#define     PCICx_CACHELS_OFFSET      0x0000000C 
#define     PCICx_LATTIM_OFFSET       0x0000000D 
#define     PCICx_HDTYPE_OFFSET       0x0000000E 
#define     PCICx_BIST_OFFSET         0x0000000F 
#define     PCICx_BAR0L_OFFSET        0x00000010
#define     PCICx_BAR0H_OFFSET        0x00000014
#define     PCICx_BAR1_OFFSET         0x00000018
#define     PCICx_BAR2L_OFFSET        0x0000001C
#define     PCICx_BAR2H_OFFSET        0x00000020

#define     PCICx_CISPTR_OFFSET       0x00000028
#define     PCICx_SBSYSVID_OFFSET     0x0000002C
#define     PCICx_SBSYSID_OFFSET      0x0000002E
#define     PCICx_EROMBA_OFFSET       0x00000030
#define     PCICx_CAP_OFFSET          0x00000034

#define     PCICx_INTLN_OFFSET        0x0000003C
#define     PCICx_INTPN_OFFSET        0x0000003D
#define     PCICx_MINGNT_OFFSET       0x0000003E
#define     PCICx_MAXLTNCY_OFFSET     0x0000003F
#define     PCICx_BRDGOPT1_OFFSET     0x00000040
#define     PCICx_BRDGOPT2_OFFSET     0x00000044
#define     PCIx_VPDCAPID_OFFSET      0x00000048
#define     PCIx_VPDNIPTR_OFFSET      0x00000049
#define     PCIx_VPDADR_OFFSET        0x0000004A
#define     PCIx_VPDDATA_OFFSET       0x0000004C
#define     PCICx_ERREN_OFFSET        0x00000050
#define     PCICx_ERRSTS_OFFSET       0x00000054
#define     PCICx_PLBBESR_OFFSET      0x00000058
#define     PCICx_PLBBEARL_OFFSET     0x0000005C
#define     PCICx_PLBBEARH_OFFSET     0x00000060
#define     PCIBx_IDR_OFFSET          0x00000064
#define     PCILx_POM0LAL_OFFSET      0x00000068
#define     PCILx_POM0LAH_OFFSET      0x0000006C
#define     PCILx_POM0SA_OFFSET       0x00000070
#define     PCILx_POM0PCIAL_OFFSET    0x00000074
#define     PCILx_POM0PCIAH_OFFSET    0x00000078
#define     PCILx_POM1LAL_OFFSET      0x0000007C
#define     PCILx_POM1LAH_OFFSET      0x00000080
#define     PCILx_POM1SA_OFFSET       0x00000084
#define     PCILx_POM1PCIAL_OFFSET    0x00000088
#define     PCILx_POM1PCIAH_OFFSET    0x0000008C
#define     PCILx_POM2SA_OFFSET       0x00000090

#define     PCILx_PIM0SAL_OFFSET      0x00000098
#define     PCILx_PIM0LAL_OFFSET      0x0000009C
#define     PCILx_PIM0LAH_OFFSET      0x000000A0
#define     PCILx_PIM1SA_OFFSET       0x000000A4
#define     PCILx_PIM1LAL_OFFSET      0x000000A8
#define     PCILx_PIM1LAH_OFFSET      0x000000AC
#define     PCILx_PIM2SAL_OFFSET      0x000000B0
#define     PCILx_PIM2LAL_OFFSET      0x000000B4
#define     PCILx_PIM2LAH_OFFSET      0x000000B8

#define     PCIMx_CAPID_OFFSET        0x000000C0
#define     PCIMx_NEXTIPTR_OFFSET     0x000000C1
#define     PCIMx_MC_OFFSET           0x000000C2
#define     PCIMx_MA_OFFSET           0x000000C4
#define     PCIMx_MUA_OFFSET          0x000000C8
#define     PCIMx_MD_OFFSET           0x000000CC
#define     PCICx_CAPID_OFFSET        0x000000D0
#define     PCICx_NIPTR_OFFSET        0x000000D1
#define     PCICx_PCIXCMD_OFFSET      0x000000D2
#define     PCICx_PMCSR_OFFSET        0x000000D4
#define     PCICx_PMCSRBSE_OFFSET     0x000000D6
#define     PCICx_DATA_OFFSET         0x000000D7
#define     PCICx_PMSCRR_OFFSET       0x000000D8
#define     PCIBx_CAPID_OFFSET        0x000000DC
#define     PCIBx_NIPTR_OFFSET        0x000000DD
#define     PCIBx_PCIXCMD_OFFSET      0x000000DE
#define     PCIBx_STS_OFFSET          0x000000E0
#define     PCIBx_ECCCS_OFFSET        0x000000E4
#define     PCIBx_ECCFA_OFFSET        0x000000E8
#define     PCIBx_ECCSA_OFFSET        0x000000EC
#define     PCIBx_ECCATT_OFFSET       0x000000F0
#define     PCILx_PIM0SAH_OFFSET      0x000000F8
#define     PCILx_PIM2SAH_OFFSET      0x000000FC

//-------------------------PCIX1--------------------------------------------------------//

#define     PCIX1_PCICx_VENDID       (PCIX1_REGS_BASE_ADDR + PCICx_VENDID_OFFSET    )
#define     PCIX1_PCICx_DEVID        (PCIX1_REGS_BASE_ADDR + PCICx_DEVID_OFFSET     )
#define     PCIX1_PCICx_CMD          (PCIX1_REGS_BASE_ADDR + PCICx_CMD_OFFSET       )
#define     PCIX1_PCICx_STATUS       (PCIX1_REGS_BASE_ADDR + PCICx_STATUS_OFFSET    )
#define     PCIX1_PCICx_REVID        (PCIX1_REGS_BASE_ADDR + PCICx_REVID_OFFSET     )
#define     PCIX1_PCICx_CLS          (PCIX1_REGS_BASE_ADDR + PCICx_CLS_OFFSET       )
#define     PCIX1_PCICx_CACHELS      (PCIX1_REGS_BASE_ADDR + PCICx_CACHELS_OFFSET   )
#define     PCIX1_PCICx_LATTIM       (PCIX1_REGS_BASE_ADDR + PCICx_LATTIM_OFFSET    )
#define     PCIX1_PCICx_HDTYPE       (PCIX1_REGS_BASE_ADDR + PCICx_HDTYPE_OFFSET    )
#define     PCIX1_PCICx_BIST         (PCIX1_REGS_BASE_ADDR + PCICx_BIST_OFFSET      )
#define     PCIX1_PCICx_BAR0L        (PCIX1_REGS_BASE_ADDR + PCICx_BAR0L_OFFSET     )
#define     PCIX1_PCICx_BAR0H        (PCIX1_REGS_BASE_ADDR + PCICx_BAR0H_OFFSET     )
#define     PCIX1_PCICx_BAR1         (PCIX1_REGS_BASE_ADDR + PCICx_BAR1_OFFSET      )
#define     PCIX1_PCICx_BAR2L        (PCIX1_REGS_BASE_ADDR + PCICx_BAR2L_OFFSET     )
#define     PCIX1_PCICx_BAR2H        (PCIX1_REGS_BASE_ADDR + PCICx_BAR2H_OFFSET     )
                                                          
#define     PCIX1_PCICx_CISPTR       (PCIX1_REGS_BASE_ADDR + PCICx_CISPTR_OFFSET    )
#define     PCIX1_PCICx_SBSYSVID     (PCIX1_REGS_BASE_ADDR + PCICx_SBSYSVID_OFFSET  )
#define     PCIX1_PCICx_SBSYSID      (PCIX1_REGS_BASE_ADDR + PCICx_SBSYSID_OFFSET   )
#define     PCIX1_PCICx_EROMBA       (PCIX1_REGS_BASE_ADDR + PCICx_EROMBA_OFFSET    )
#define     PCIX1_PCICx_CAP          (PCIX1_REGS_BASE_ADDR + PCICx_CAP_OFFSET       )
                                                                        
#define     PCIX1_PCICx_INTLN        (PCIX1_REGS_BASE_ADDR + PCICx_INTLN_OFFSET     )
#define     PCIX1_PCICx_INTPN        (PCIX1_REGS_BASE_ADDR + PCICx_INTPN_OFFSET     )
#define     PCIX1_PCICx_MINGNT       (PCIX1_REGS_BASE_ADDR + PCICx_MINGNT_OFFSET    )
#define     PCIX1_PCICx_MAXLTNCY     (PCIX1_REGS_BASE_ADDR + PCICx_MAXLTNCY_OFFSET  )
#define     PCIX1_PCICx_BRDGOPT1     (PCIX1_REGS_BASE_ADDR + PCICx_BRDGOPT1_OFFSET  )
#define     PCIX1_PCICx_BRDGOPT2     (PCIX1_REGS_BASE_ADDR + PCICx_BRDGOPT2_OFFSET  )
#define     PCIX1_PCIx_VPDCAPID      (PCIX1_REGS_BASE_ADDR + PCIx_VPDCAPID_OFFSET   )
#define     PCIX1_PCIx_VPDNIPTR      (PCIX1_REGS_BASE_ADDR + PCIx_VPDNIPTR_OFFSET   )
#define     PCIX1_PCIx_VPDADR        (PCIX1_REGS_BASE_ADDR + PCIx_VPDADR_OFFSET     )
#define     PCIX1_PCIx_VPDDATA       (PCIX1_REGS_BASE_ADDR + PCIx_VPDDATA_OFFSET    )
#define     PCIX1_PCICx_ERREN        (PCIX1_REGS_BASE_ADDR + PCICx_ERREN_OFFSET     )
#define     PCIX1_PCICx_ERRSTS       (PCIX1_REGS_BASE_ADDR + PCICx_ERRSTS_OFFSET    )
#define     PCIX1_PCICx_PLBBESR      (PCIX1_REGS_BASE_ADDR + PCICx_PLBBESR_OFFSET   )
#define     PCIX1_PCICx_PLBBEARL     (PCIX1_REGS_BASE_ADDR + PCICx_PLBBEARL_OFFSET  )
#define     PCIX1_PCICx_PLBBEARH     (PCIX1_REGS_BASE_ADDR + PCICx_PLBBEARH_OFFSET  )
#define     PCIX1_PCIBx_IDR          (PCIX1_REGS_BASE_ADDR + PCIBx_IDR_OFFSET       )
#define     PCIX1_PCILx_POM0LAL      (PCIX1_REGS_BASE_ADDR + PCILx_POM0LAL_OFFSET   )
#define     PCIX1_PCILx_POM0LAH      (PCIX1_REGS_BASE_ADDR + PCILx_POM0LAH_OFFSET   )
#define     PCIX1_PCILx_POM0SA       (PCIX1_REGS_BASE_ADDR + PCILx_POM0SA_OFFSET    )
#define     PCIX1_PCILx_POM0PCIAL    (PCIX1_REGS_BASE_ADDR + PCILx_POM0PCIAL_OFFSET )
#define     PCIX1_PCILx_POM0PCIAH    (PCIX1_REGS_BASE_ADDR + PCILx_POM0PCIAH_OFFSET )
#define     PCIX1_PCILx_POM1LAL      (PCIX1_REGS_BASE_ADDR + PCILx_POM1LAL_OFFSET   )
#define     PCIX1_PCILx_POM1LAH      (PCIX1_REGS_BASE_ADDR + PCILx_POM1LAH_OFFSET   )
#define     PCIX1_PCILx_POM1SA       (PCIX1_REGS_BASE_ADDR + PCILx_POM1SA_OFFSET    )
#define     PCIX1_PCILx_POM1PCIAL    (PCIX1_REGS_BASE_ADDR + PCILx_POM1PCIAL_OFFSET )
#define     PCIX1_PCILx_POM1PCIAH    (PCIX1_REGS_BASE_ADDR + PCILx_POM1PCIAH_OFFSET )
#define     PCIX1_PCILx_POM2SA       (PCIX1_REGS_BASE_ADDR + PCILx_POM2SA_OFFSET    )
                  
#define     PCIX1_PCILx_PIM0SAL      (PCIX1_REGS_BASE_ADDR + PCILx_PIM0SAL_OFFSET   )
#define     PCIX1_PCILx_PIM0LAL      (PCIX1_REGS_BASE_ADDR + PCILx_PIM0LAL_OFFSET   )
#define     PCIX1_PCILx_PIM0LAH      (PCIX1_REGS_BASE_ADDR + PCILx_PIM0LAH_OFFSET   )
#define     PCIX1_PCILx_PIM1SA       (PCIX1_REGS_BASE_ADDR + PCILx_PIM1SA_OFFSET    )
#define     PCIX1_PCILx_PIM1LAL      (PCIX1_REGS_BASE_ADDR + PCILx_PIM1LAL_OFFSET   )
#define     PCIX1_PCILx_PIM1LAH      (PCIX1_REGS_BASE_ADDR + PCILx_PIM1LAH_OFFSET   )
#define     PCIX1_PCILx_PIM2SAL      (PCIX1_REGS_BASE_ADDR + PCILx_PIM2SAL_OFFSET   )
#define     PCIX1_PCILx_PIM2LAL      (PCIX1_REGS_BASE_ADDR + PCILx_PIM2LAL_OFFSET   )
#define     PCIX1_PCILx_PIM2LAH      (PCIX1_REGS_BASE_ADDR + PCILx_PIM2LAH_OFFSET   )
                  
#define     PCIX1_PCIMx_CAPID        (PCIX1_REGS_BASE_ADDR + PCIMx_CAPID_OFFSET     )
#define     PCIX1_PCIMx_NEXTIPTR     (PCIX1_REGS_BASE_ADDR + PCIMx_NEXTIPTR_OFFSET  )
#define     PCIX1_PCIMx_MC           (PCIX1_REGS_BASE_ADDR + PCIMx_MC_OFFSET        )
#define     PCIX1_PCIMx_MA           (PCIX1_REGS_BASE_ADDR + PCIMx_MA_OFFSET        )
#define     PCIX1_PCIMx_MUA          (PCIX1_REGS_BASE_ADDR + PCIMx_MUA_OFFSET       )
#define     PCIX1_PCIMx_MD           (PCIX1_REGS_BASE_ADDR + PCIMx_MD_OFFSET        )
#define     PCIX1_PCICx_CAPID        (PCIX1_REGS_BASE_ADDR + PCICx_CAPID_OFFSET     )
#define     PCIX1_PCICx_NIPTR        (PCIX1_REGS_BASE_ADDR + PCICx_NIPTR_OFFSET     )
#define     PCIX1_PCICx_PCIXCMD      (PCIX1_REGS_BASE_ADDR + PCICx_PCIXCMD_OFFSET   )
#define     PCIX1_PCICx_PMCSR        (PCIX1_REGS_BASE_ADDR + PCICx_PMCSR_OFFSET     )
#define     PCIX1_PCICx_PMCSRBSE     (PCIX1_REGS_BASE_ADDR + PCICx_PMCSRBSE_OFFSET  )
#define     PCIX1_PCICx_DATA         (PCIX1_REGS_BASE_ADDR + PCICx_DATA_OFFSET      )
#define     PCIX1_PCICx_PMSCRR       (PCIX1_REGS_BASE_ADDR + PCICx_PMSCRR_OFFSET    )
#define     PCIX1_PCIBx_CAPID        (PCIX1_REGS_BASE_ADDR + PCIBx_CAPID_OFFSET     )
#define     PCIX1_PCIBx_NIPTR        (PCIX1_REGS_BASE_ADDR + PCIBx_NIPTR_OFFSET     )
#define     PCIX1_PCIBx_PCIXCMD      (PCIX1_REGS_BASE_ADDR + PCIBx_PCIXCMD_OFFSET   )
#define     PCIX1_PCIBx_STS          (PCIX1_REGS_BASE_ADDR + PCIBx_STS_OFFSET       )
#define     PCIX1_PCIBx_ECCCS        (PCIX1_REGS_BASE_ADDR + PCIBx_ECCCS_OFFSET     )
#define     PCIX1_PCIBx_ECCFA        (PCIX1_REGS_BASE_ADDR + PCIBx_ECCFA_OFFSET     )
#define     PCIX1_PCIBx_ECCSA        (PCIX1_REGS_BASE_ADDR + PCIBx_ECCSA_OFFSET     )
#define     PCIX1_PCIBx_ECCATT       (PCIX1_REGS_BASE_ADDR + PCIBx_ECCATT_OFFSET    )
#define     PCIX1_PCILx_PIM0SAH      (PCIX1_REGS_BASE_ADDR + PCILx_PIM0SAH_OFFSET   )
#define     PCIX1_PCILx_PIM2SAH      (PCIX1_REGS_BASE_ADDR + PCILx_PIM2SAH_OFFSET   )

#define     PCIX1_PCIBx_CID          (PCIX1_REGS_BASE_ADDR + 0xDE8)
#define     PCIX1_PCIBx_RID          (PCIX1_REGS_BASE_ADDR + 0xDEC)

#define     PCIX1_PCISx_MSGIL        (PCIX1_REGS_BASE_ADDR + 0x1100)
#define     PCIX1_PCISx_MSGIH        (PCIX1_REGS_BASE_ADDR + 0x1104)
#define     PCIX1_PCISx_MSGOL        (PCIX1_REGS_BASE_ADDR + 0x1108)
#define     PCIX1_PCISx_MSGOH        (PCIX1_REGS_BASE_ADDR + 0x110C)

#define     PCIX1_PCISx_IM           (PCIX1_REGS_BASE_ADDR + 0x11F8)

#define     PCIX1_PCIS_CONFIG_ADDR   (PCIX1_CONFIG_BASE_ADDR + 0x0)
#define     PCIX1_PCIS_CONFIG_DATA   (PCIX1_CONFIG_BASE_ADDR + 0x4)




//-------------------------PCIX2--------------------------------------------------------//

#define     PCIX2_PCICx_VENDID       (PCIX2_REGS_BASE_ADDR + PCICx_VENDID_OFFSET    )
#define     PCIX2_PCICx_DEVID        (PCIX2_REGS_BASE_ADDR + PCICx_DEVID_OFFSET     )
#define     PCIX2_PCICx_CMD          (PCIX2_REGS_BASE_ADDR + PCICx_CMD_OFFSET       )
#define     PCIX2_PCICx_STATUS       (PCIX2_REGS_BASE_ADDR + PCICx_STATUS_OFFSET    )
#define     PCIX2_PCICx_REVID        (PCIX2_REGS_BASE_ADDR + PCICx_REVID_OFFSET     )
#define     PCIX2_PCICx_CLS          (PCIX2_REGS_BASE_ADDR + PCICx_CLS_OFFSET       )
#define     PCIX2_PCICx_CACHELS      (PCIX2_REGS_BASE_ADDR + PCICx_CACHELS_OFFSET   )
#define     PCIX2_PCICx_LATTIM       (PCIX2_REGS_BASE_ADDR + PCICx_LATTIM_OFFSET    )
#define     PCIX2_PCICx_HDTYPE       (PCIX2_REGS_BASE_ADDR + PCICx_HDTYPE_OFFSET    )
#define     PCIX2_PCICx_BIST         (PCIX2_REGS_BASE_ADDR + PCICx_BIST_OFFSET      )
#define     PCIX2_PCICx_BAR0L        (PCIX2_REGS_BASE_ADDR + PCICx_BAR0L_OFFSET     )
#define     PCIX2_PCICx_BAR0H        (PCIX2_REGS_BASE_ADDR + PCICx_BAR0H_OFFSET     )
#define     PCIX2_PCICx_BAR1         (PCIX2_REGS_BASE_ADDR + PCICx_BAR1_OFFSET      )
#define     PCIX2_PCICx_BAR2L        (PCIX2_REGS_BASE_ADDR + PCICx_BAR2L_OFFSET     )
#define     PCIX2_PCICx_BAR2H        (PCIX2_REGS_BASE_ADDR + PCICx_BAR2H_OFFSET     )
                                                        
#define     PCIX2_PCICx_CISPTR       (PCIX2_REGS_BASE_ADDR + PCICx_CISPTR_OFFSET    )
#define     PCIX2_PCICx_SBSYSVID     (PCIX2_REGS_BASE_ADDR + PCICx_SBSYSVID_OFFSET  )
#define     PCIX2_PCICx_SBSYSID      (PCIX2_REGS_BASE_ADDR + PCICx_SBSYSID_OFFSET   )
#define     PCIX2_PCICx_EROMBA       (PCIX2_REGS_BASE_ADDR + PCICx_EROMBA_OFFSET    )
#define     PCIX2_PCICx_CAP          (PCIX2_REGS_BASE_ADDR + PCICx_CAP_OFFSET       )
                                                                      
#define     PCIX2_PCICx_INTLN        (PCIX2_REGS_BASE_ADDR + PCICx_INTLN_OFFSET     )
#define     PCIX2_PCICx_INTPN        (PCIX2_REGS_BASE_ADDR + PCICx_INTPN_OFFSET     )
#define     PCIX2_PCICx_MINGNT       (PCIX2_REGS_BASE_ADDR + PCICx_MINGNT_OFFSET    )
#define     PCIX2_PCICx_MAXLTNCY     (PCIX2_REGS_BASE_ADDR + PCICx_MAXLTNCY_OFFSET  )
#define     PCIX2_PCICx_BRDGOPT1     (PCIX2_REGS_BASE_ADDR + PCICx_BRDGOPT1_OFFSET  )
#define     PCIX2_PCICx_BRDGOPT2     (PCIX2_REGS_BASE_ADDR + PCICx_BRDGOPT2_OFFSET  )
#define     PCIX2_PCIx_VPDCAPID      (PCIX2_REGS_BASE_ADDR + PCIx_VPDCAPID_OFFSET   )
#define     PCIX2_PCIx_VPDNIPTR      (PCIX2_REGS_BASE_ADDR + PCIx_VPDNIPTR_OFFSET   )
#define     PCIX2_PCIx_VPDADR        (PCIX2_REGS_BASE_ADDR + PCIx_VPDADR_OFFSET     )
#define     PCIX2_PCIx_VPDDATA       (PCIX2_REGS_BASE_ADDR + PCIx_VPDDATA_OFFSET    )
#define     PCIX2_PCICx_ERREN        (PCIX2_REGS_BASE_ADDR + PCICx_ERREN_OFFSET     )
#define     PCIX2_PCICx_ERRSTS       (PCIX2_REGS_BASE_ADDR + PCICx_ERRSTS_OFFSET    )
#define     PCIX2_PCICx_PLBBESR      (PCIX2_REGS_BASE_ADDR + PCICx_PLBBESR_OFFSET   )
#define     PCIX2_PCICx_PLBBEARL     (PCIX2_REGS_BASE_ADDR + PCICx_PLBBEARL_OFFSET  )
#define     PCIX2_PCICx_PLBBEARH     (PCIX2_REGS_BASE_ADDR + PCICx_PLBBEARH_OFFSET  )
#define     PCIX2_PCIBx_IDR          (PCIX2_REGS_BASE_ADDR + PCIBx_IDR_OFFSET       )
#define     PCIX2_PCILx_POM0LAL      (PCIX2_REGS_BASE_ADDR + PCILx_POM0LAL_OFFSET   )
#define     PCIX2_PCILx_POM0LAH      (PCIX2_REGS_BASE_ADDR + PCILx_POM0LAH_OFFSET   )
#define     PCIX2_PCILx_POM0SA       (PCIX2_REGS_BASE_ADDR + PCILx_POM0SA_OFFSET    )
#define     PCIX2_PCILx_POM0PCIAL    (PCIX2_REGS_BASE_ADDR + PCILx_POM0PCIAL_OFFSET )
#define     PCIX2_PCILx_POM0PCIAH    (PCIX2_REGS_BASE_ADDR + PCILx_POM0PCIAH_OFFSET )
#define     PCIX2_PCILx_POM1LAL      (PCIX2_REGS_BASE_ADDR + PCILx_POM1LAL_OFFSET   )
#define     PCIX2_PCILx_POM1LAH      (PCIX2_REGS_BASE_ADDR + PCILx_POM1LAH_OFFSET   )
#define     PCIX2_PCILx_POM1SA       (PCIX2_REGS_BASE_ADDR + PCILx_POM1SA_OFFSET    )
#define     PCIX2_PCILx_POM1PCIAL    (PCIX2_REGS_BASE_ADDR + PCILx_POM1PCIAL_OFFSET )
#define     PCIX2_PCILx_POM1PCIAH    (PCIX2_REGS_BASE_ADDR + PCILx_POM1PCIAH_OFFSET )
#define     PCIX2_PCILx_POM2SA       (PCIX2_REGS_BASE_ADDR + PCILx_POM2SA_OFFSET    )
                 
#define     PCIX2_PCILx_PIM0SAL      (PCIX2_REGS_BASE_ADDR + PCILx_PIM0SAL_OFFSET   )
#define     PCIX2_PCILx_PIM0LAL      (PCIX2_REGS_BASE_ADDR + PCILx_PIM0LAL_OFFSET   )
#define     PCIX2_PCILx_PIM0LAH      (PCIX2_REGS_BASE_ADDR + PCILx_PIM0LAH_OFFSET   )
#define     PCIX2_PCILx_PIM1SA       (PCIX2_REGS_BASE_ADDR + PCILx_PIM1SA_OFFSET    )
#define     PCIX2_PCILx_PIM1LAL      (PCIX2_REGS_BASE_ADDR + PCILx_PIM1LAL_OFFSET   )
#define     PCIX2_PCILx_PIM1LAH      (PCIX2_REGS_BASE_ADDR + PCILx_PIM1LAH_OFFSET   )
#define     PCIX2_PCILx_PIM2SAL      (PCIX2_REGS_BASE_ADDR + PCILx_PIM2SAL_OFFSET   )
#define     PCIX2_PCILx_PIM2LAL      (PCIX2_REGS_BASE_ADDR + PCILx_PIM2LAL_OFFSET   )
#define     PCIX2_PCILx_PIM2LAH      (PCIX2_REGS_BASE_ADDR + PCILx_PIM2LAH_OFFSET   )
                 
#define     PCIX2_PCIMx_CAPID        (PCIX2_REGS_BASE_ADDR + PCIMx_CAPID_OFFSET     )
#define     PCIX2_PCIMx_NEXTIPTR     (PCIX2_REGS_BASE_ADDR + PCIMx_NEXTIPTR_OFFSET  )
#define     PCIX2_PCIMx_MC           (PCIX2_REGS_BASE_ADDR + PCIMx_MC_OFFSET        )
#define     PCIX2_PCIMx_MA           (PCIX2_REGS_BASE_ADDR + PCIMx_MA_OFFSET        )
#define     PCIX2_PCIMx_MUA          (PCIX2_REGS_BASE_ADDR + PCIMx_MUA_OFFSET       )
#define     PCIX2_PCIMx_MD           (PCIX2_REGS_BASE_ADDR + PCIMx_MD_OFFSET        )
#define     PCIX2_PCICx_CAPID        (PCIX2_REGS_BASE_ADDR + PCICx_CAPID_OFFSET     )
#define     PCIX2_PCICx_NIPTR        (PCIX2_REGS_BASE_ADDR + PCICx_NIPTR_OFFSET     )
#define     PCIX2_PCICx_PCIXCMD      (PCIX2_REGS_BASE_ADDR + PCICx_PCIXCMD_OFFSET   )
#define     PCIX2_PCICx_PMCSR        (PCIX2_REGS_BASE_ADDR + PCICx_PMCSR_OFFSET     )
#define     PCIX2_PCICx_PMCSRBSE     (PCIX2_REGS_BASE_ADDR + PCICx_PMCSRBSE_OFFSET  )
#define     PCIX2_PCICx_DATA         (PCIX2_REGS_BASE_ADDR + PCICx_DATA_OFFSET      )
#define     PCIX2_PCICx_PMSCRR       (PCIX2_REGS_BASE_ADDR + PCICx_PMSCRR_OFFSET    )
#define     PCIX2_PCIBx_CAPID        (PCIX2_REGS_BASE_ADDR + PCIBx_CAPID_OFFSET     )
#define     PCIX2_PCIBx_NIPTR        (PCIX2_REGS_BASE_ADDR + PCIBx_NIPTR_OFFSET     )
#define     PCIX2_PCIBx_PCIXCMD      (PCIX2_REGS_BASE_ADDR + PCIBx_PCIXCMD_OFFSET   )
#define     PCIX2_PCIBx_STS          (PCIX2_REGS_BASE_ADDR + PCIBx_STS_OFFSET       )
#define     PCIX2_PCIBx_ECCCS        (PCIX2_REGS_BASE_ADDR + PCIBx_ECCCS_OFFSET     )
#define     PCIX2_PCIBx_ECCFA        (PCIX2_REGS_BASE_ADDR + PCIBx_ECCFA_OFFSET     )
#define     PCIX2_PCIBx_ECCSA        (PCIX2_REGS_BASE_ADDR + PCIBx_ECCSA_OFFSET     )
#define     PCIX2_PCIBx_ECCATT       (PCIX2_REGS_BASE_ADDR + PCIBx_ECCATT_OFFSET    )
#define     PCIX2_PCILx_PIM0SAH      (PCIX2_REGS_BASE_ADDR + PCILx_PIM0SAH_OFFSET   )
#define     PCIX2_PCILx_PIM2SAH      (PCIX2_REGS_BASE_ADDR + PCILx_PIM2SAH_OFFSET   )

#define     PCIX2_PCIBx_CID          (PCIX2_REGS_BASE_ADDR + 0xDE8)
#define     PCIX2_PCIBx_RID          (PCIX2_REGS_BASE_ADDR + 0xDEC)

#define     PCIX2_PCISx_MSGIL        (PCIX2_REGS_BASE_ADDR + 0x1100)
#define     PCIX2_PCISx_MSGIH        (PCIX2_REGS_BASE_ADDR + 0x1104)
#define     PCIX2_PCISx_MSGOL        (PCIX2_REGS_BASE_ADDR + 0x1108)
#define     PCIX2_PCISx_MSGOH        (PCIX2_REGS_BASE_ADDR + 0x110C)

#define     PCIX2_PCISx_IM           (PCIX2_REGS_BASE_ADDR + 0x11F8)

#define     PCIX2_PCIS_CONFIG_ADDR   (PCIX2_CONFIG_BASE_ADDR + 0x0)
#define     PCIX2_PCIS_CONFIG_DATA   (PCIX2_CONFIG_BASE_ADDR + 0x4)




