// u_axi_sub.u_peri_subsys.u_peri_ahb_matrix.uperi_ahb_matrix.u_peri_matrix_decoders0.p_addr_out_port_comb
// CCSR S2/PERI AHB S10: SSI Controller : 0xEB78_0000 ~ 0xEB7F_FFFF / 512K
// CCSR S2/PERI AHB S9 : SSI CFG        : 0xEB02_0000 ~ 0xEB02_0FFF / 4K
#define SSI_INT_NUM                 102
#define SSI_CFG                     0xEB020000
#define SSI_CFG_RESERVED            0xEB020008
#define SSI_BASE_ADDR               0xEB780000
#define SSI_1_BASE_ADDR             0xEB788000     // SSI_1_BASE_ADDR is not used. It is only for env/lib/mpu.c.
#define SSI_XIP_JUMP_ADDR           0xE1000000     // same as 0xEC00_0000 in CCP907T

#define SSI_CTRLR0                  (SSI_BASE_ADDR + 0x00)
#define SSI_CTRLR1                  (SSI_BASE_ADDR + 0x04)
#define SSI_SSIENR                  (SSI_BASE_ADDR + 0x08)
#define SSI_MWCR                    (SSI_BASE_ADDR + 0x0c)
#define SSI_SER                     (SSI_BASE_ADDR + 0x10)
#define SSI_BAUDR                   (SSI_BASE_ADDR + 0x14)
#define SSI_TXFTLR                  (SSI_BASE_ADDR + 0x18)
#define SSI_RXFTLR                  (SSI_BASE_ADDR + 0x1c)
#define SSI_TXFLR                   (SSI_BASE_ADDR + 0x20)
#define SSI_RXFLR                   (SSI_BASE_ADDR + 0x24)
#define SSI_SR                      (SSI_BASE_ADDR + 0x28)
#define SSI_IMR                     (SSI_BASE_ADDR + 0x2c)
#define SSI_ISR                     (SSI_BASE_ADDR + 0x30)
#define SSI_RISR                    (SSI_BASE_ADDR + 0x34)
#define SSI_TXOICR                  (SSI_BASE_ADDR + 0x38)
#define SSI_RXOICR                  (SSI_BASE_ADDR + 0x3c)
#define SSI_RXUICR                  (SSI_BASE_ADDR + 0x40)
#define SSI_MSTICR                  (SSI_BASE_ADDR + 0x44)
#define SSI_ICR                     (SSI_BASE_ADDR + 0x48)
#define SSI_DMACR                   (SSI_BASE_ADDR + 0x4c)
#define SSI_DMATDLR                 (SSI_BASE_ADDR + 0x50)
#define SSI_DMARDLR                 (SSI_BASE_ADDR + 0x54)
#define SSI_IDR                     (SSI_BASE_ADDR + 0x58)
#define SSI_SSIC_VERSION_ID         (SSI_BASE_ADDR + 0x5c)
#define SSI_DRx                     (SSI_BASE_ADDR + 0x60)
#define SSI_RX_SAMPLE_DELAY         (SSI_BASE_ADDR + 0xf0)
#define SSI_SPI_CTRLR0              (SSI_BASE_ADDR + 0xf4)
#define SSI_DDR_DRIVE_EDGE          (SSI_BASE_ADDR + 0xf8)
#define SSI_XIP_MODE_BITS           (SSI_BASE_ADDR + 0xfc)
#define SSI_XIP_INCR_INST           (SSI_BASE_ADDR + 0x100)
#define SSI_XIP_WRAP_INST           (SSI_BASE_ADDR + 0x104)
#define SSI_XIP_CTRL                (SSI_BASE_ADDR + 0x108)
#define SSI_CTL_RESERVED            (SSI_BASE_ADDR + 0x110)

#define SSI_1_CTRLR0                  (SSI_1_BASE_ADDR + 0x00)
#define SSI_1_CTRLR1                  (SSI_1_BASE_ADDR + 0x04)
#define SSI_1_SSIENR                  (SSI_1_BASE_ADDR + 0x08)
#define SSI_1_MWCR                    (SSI_1_BASE_ADDR + 0x0c)
#define SSI_1_SER                     (SSI_1_BASE_ADDR + 0x10)
#define SSI_1_BAUDR                   (SSI_1_BASE_ADDR + 0x14)
#define SSI_1_TXFTLR                  (SSI_1_BASE_ADDR + 0x18)
#define SSI_1_RXFTLR                  (SSI_1_BASE_ADDR + 0x1c)
#define SSI_1_TXFLR                   (SSI_1_BASE_ADDR + 0x20)
#define SSI_1_RXFLR                   (SSI_1_BASE_ADDR + 0x24)
#define SSI_1_SR                      (SSI_1_BASE_ADDR + 0x28)
#define SSI_1_IMR                     (SSI_1_BASE_ADDR + 0x2c)
#define SSI_1_ISR                     (SSI_1_BASE_ADDR + 0x30)
#define SSI_1_RISR                    (SSI_1_BASE_ADDR + 0x34)
#define SSI_1_TXOICR                  (SSI_1_BASE_ADDR + 0x38)
#define SSI_1_RXOICR                  (SSI_1_BASE_ADDR + 0x3c)
#define SSI_1_RXUICR                  (SSI_1_BASE_ADDR + 0x40)
#define SSI_1_MSTICR                  (SSI_1_BASE_ADDR + 0x44)
#define SSI_1_ICR                     (SSI_1_BASE_ADDR + 0x48)
#define SSI_1_DMACR                   (SSI_1_BASE_ADDR + 0x4c)
#define SSI_1_DMATDLR                 (SSI_1_BASE_ADDR + 0x50)
#define SSI_1_DMARDLR                 (SSI_1_BASE_ADDR + 0x54)
#define SSI_1_IDR                     (SSI_1_BASE_ADDR + 0x58)
#define SSI_1_SSIC_VERSION_ID         (SSI_1_BASE_ADDR + 0x5c)
#define SSI_1_DRx                     (SSI_1_BASE_ADDR + 0x60)
#define SSI_1_RX_SAMPLE_DELAY         (SSI_1_BASE_ADDR + 0xf0)
#define SSI_1_SPI_CTRLR0              (SSI_1_BASE_ADDR + 0xf4)
#define SSI_1_DDR_DRIVE_EDGE          (SSI_1_BASE_ADDR + 0xf8)
#define SSI_1_XIP_MODE_BITS           (SSI_1_BASE_ADDR + 0xfc)
#define SSI_1_XIP_INCR_INST           (SSI_1_BASE_ADDR + 0x100)
#define SSI_1_XIP_WRAP_INST           (SSI_1_BASE_ADDR + 0x104)
#define SSI_1_XIP_CTRL                (SSI_1_BASE_ADDR + 0x108)
